{{
  config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='skey'
  )
}}

with gl_accounthier_flat as (
SELECT 

 ATT.KTOPL||'-'|| ATT.SAKNR||'-'||nvl(LANGU,'') as skey,
  
ATT.KTOPL KTOPL,
ATT.SAKNR SAKNR,
BILKT,
GVTYP,
VBUND,
XBILK,
SAKAN,
ERDAT,
ERNAM,
KTOKS,
XLOEV,
XSPEA,
XSPEB,
XSPEP,
FUNC_AREA,
MUSTR,
LANGU,
TXTSH,
TXTLG,
GLHIER.L1_TXTSH,
GLHIER.L1_TXTMD,
GLHIER.L1_TXTLG,
GLHIER.L4_TXTSH,
GLHIER.L4_TXTMD,
GLHIER.L4_TXTLG,
GLHIER.L3_TXTSH,
GLHIER.L3_TXTMD,
GLHIER.L3_TXTLG,
GLHIER.L2_TXTSH,
GLHIER.L2_TXTMD,
GLHIER.L2_TXTLG,
GLHIER.L4_NODEID, 
GLHIER.L4_NODENAME,
GLHIER.L3_NODEID ,
GLHIER.L3_NODENAME,
GLHIER.L2_NODEID ,
GLHIER.L2_NODENAME,
GLHIER.L1_NODEID ,
GLHIER.L1_NODENAME,
GLHIER.L5_NODEID,
GLHIER.L5_NODENAME,
GLHIER.L5_KTOPL ,
GLHIER.L5_SAKNR 
FROM "ARRAY_DB"."ARRAY_DB_EDW".GL_ACCOUNT_ATTR ATT 
LEFT OUTER JOIN "ARRAY_DB"."ARRAY_DB_EDW".GL_ACCOUNT_TEXT TXT ON (ATT.KTOPL=TXT.KTOPL AND ATT.SAKNR=TXT.SAKNR)
LEFT OUTER JOIN (
select 
TL5.L5_NODEID , 
TL5.L5_NODENAME,        
TL5.L5_KTOPL    ,
TL5.L5_SAKNR,

TL4.L4_NODEID,  
TL4.L4_NODENAME, 
TL4.L4_TXTSH    ,
TL4.L4_TXTMD    ,
TL4.L4_TXTLG ,

TL3.L3_NODEID , 
TL3.L3_NODENAME,    
TL3.L3_TXTSH    ,
TL3.L3_TXTMD    ,
TL3.L3_TXTLG ,

TL2.L2_NODEID , 
TL2.L2_NODENAME,    
TL2.L2_TXTSH    ,
TL2.L2_TXTMD    ,
TL2.L2_TXTLG ,

TL1.L1_NODEID , 
TL1.L1_NODENAME,    
TL1.L1_TXTSH    ,
TL1.L1_TXTMD    ,
TL1.L1_TXTLG    
 from 
(SELECT
    NODEID L5_NODEID,
    NODENAME L5_NODENAME,
    KTOPL L5_KTOPL,
    SAKNR L5_SAKNR
FROM ARRAY_DB.ARRAY_DB_EDW.GL_ACCOUNT_T011_HIER  WHERE TLEVEL='05') TL5
LEFT outer join
(SELECT 
    L5.NODEID AS L5_NODEID,
    L4.NODEID AS L4_NODEID,
    L4.NODENAME AS L4_NODENAME,
    L4.TXTSH AS L4_TXTSH,
    L4.TXTMD AS L4_TXTMD,
    L4.TXTLG AS L4_TXTLG
FROM ARRAY_DB.ARRAY_DB_EDW.GL_ACCOUNT_T011_HIER L4 INNER JOIN ARRAY_DB.ARRAY_DB_EDW.GL_ACCOUNT_T011_HIER L5
ON L4.NODEID=L5.PARENTID WHERE L5.TLEVEL='05' AND L4.TLEVEL='04') TL4
on (TL4.L5_NODEID=TL5.L5_NODEID)
left outer join
(SELECT 
    L4.NODEID AS L4_NODEID,
    L3.NODEID AS L3_NODEID,
    L3.NODENAME AS L3_NODENAME,
    L3.TXTSH AS L3_TXTSH,
    L3.TXTMD AS L3_TXTMD,
    L3.TXTLG AS L3_TXTLG
FROM ARRAY_DB.ARRAY_DB_EDW.GL_ACCOUNT_T011_HIER L3 INNER JOIN ARRAY_DB.ARRAY_DB_EDW.GL_ACCOUNT_T011_HIER L4
ON L3.NODEID=L4.PARENTID WHERE L4.TLEVEL='04' AND L3.TLEVEL='03') TL3
on TL3.L4_NODEID=TL4.L4_NODEID
left outer join
(SELECT 
    L3.NODEID AS L3_NODEID,
    L2.NODEID AS L2_NODEID,
    L2.NODENAME AS L2_NODENAME,
    L2.TXTSH AS L2_TXTSH,
    L2.TXTMD AS L2_TXTMD,
    L2.TXTLG AS L2_TXTLG
FROM ARRAY_DB.ARRAY_DB_EDW.GL_ACCOUNT_T011_HIER L2 INNER JOIN ARRAY_DB.ARRAY_DB_EDW.GL_ACCOUNT_T011_HIER L3
ON L2.NODEID=L3.PARENTID WHERE L3.TLEVEL='03' AND L2.TLEVEL='02') TL2
on TL2.L3_NODEID=TL3.L3_NODEID
left outer join 
(SELECT 
    L2.NODEID AS L2_NODEID,
    L1.NODEID AS L1_NODEID,
    L1.NODENAME AS L1_NODENAME,
    L1.TXTSH AS L1_TXTSH,
    L1.TXTMD AS L1_TXTMD,
    L1.TXTLG AS L1_TXTLG
FROM ARRAY_DB.ARRAY_DB_EDW.GL_ACCOUNT_T011_HIER L1 INNER JOIN ARRAY_DB.ARRAY_DB_EDW.GL_ACCOUNT_T011_HIER L2
ON L1.NODEID=L2.PARENTID WHERE L2.TLEVEL='02' AND L1.TLEVEL='01') TL1
on TL1.L2_NODEID=TL2.L2_NODEID
  ) GLHIER
  on (ATT.KTOPL=GLHIER.L5_KTOPL and ATT.SAKNR=L5_SAKNR)
 WHERE LANGU='E'
  )

  select * from gl_accounthier_flat
