{{
  config(
    materialized='incremental',
    incremental_strategy='merge',
	unique_key='COSTCENTER_ID'
  )
}}

--	CCA.KOKRS||'-'||CCA.KOSTL||'-'||CCA.DATETO||'-'||NVL(CCT.LANGU,'') as ID,
with dim_costcenter_flat as (
SELECT
	CCA.KOKRS||'-'||CCA.KOSTL as COSTCENTER_ID,

	CCA.KOKRS,
	CCA.KOSTL,
	CCA.DATETO,

	NVL(CCT.LANGU,'') AS LANGU,

	CCA.DATEFROM,
	CCA.VERAK,
	CCA.BUKRS,
	CCA.GSBER,
	CCA.KOSAR,
	CCA.WAERS,
	CCA.PRCTR,
	CCA.BKZKP,
	CCA.PKZKP,
	CCA.VERAK_USER,
	CCA.KALSM,
	CCA.TXJCD,
	CCA.WERKS,
	CCA.LOGSYSTEM,
	CCA.ERSDA,
	CCA.USNAM,
	CCA.BKZKS,
	CCA.BKZER,
	CCA.BKZOB,
	CCA.PKZKS,
	CCA.PKZER,
	CCA.VMETH,
	CCA.MGEFL,
	CCA.ABTEI,
	CCA.NKOST,
	CCA.KVEWE,
	CCA.KAPPL,
	CCA.KOSZSCHL,
	CCA.LAND1,
	CCA.ANRED,
	CCA.NAME1,
	CCA.NAME2,
	CCA.NAME3,
	CCA.NAME4,
	CCA.ORT01,
	CCA.ORT02,
	CCA.STRAS,
	CCA.PFACH,
	CCA.PSTLZ,
	CCA.PSTL2,
	CCA.REGIO,
	CCA.SPRAS,
	CCA.TELBX,
	CCA.TELF1,
	CCA.TELF2,
	CCA.TELFX,
	CCA.TELTX,
	CCA.TELX1,
	CCA.DATLT,
	CCA.DRNAM,
	CCA.KHINR,
	CCA.CCKEY,
	CCA.KOMPL,
	CCA.STAKZ,
	CCA.OBJNR,
	CCA.FUNKT,
	CCA.AFUNK,
	CCA.CPI_TEMPL,
	CCA.CPD_TEMPL,
	CCA.FUNC_AREA,
	CCA.SCI_TEMPL,
	CCA.SCD_TEMPL,
	CCA.VNAME,
	CCA.RECID,
	CCA.ETYPE,
	CCA.JV_OTYPE,
	CCA.JV_JIBCL,
	CCA.JV_JIBSA,

	CCT.TXTSH,
	CCT.TXTMD,
	CCT.TXTMC,

	CCHFS.L1_TXTSH,
	CCHFS.L1_TXTMD,
	CCHFS.L1_TXTLG,

	CCHFS.L1_NODEID,
	CCHFS.L1_NODENAME,
	CCHFS.L2_NODEID,
	CCHFS.L2_NODENAME

FROM ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_ATTR CCA 
LEFT OUTER JOIN ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_TEXT CCT 
ON (CCA.KOKRS=CCT.KOKRS and CCA.KOSTL=CCT.KOSTL and CCA.DATETO=CCT.DATETO)
LEFT OUTER JOIN (SELECT 
	TL2.L2_NODEID,
	TL2.L2_NODENAME,
	TL2.L2_KOKRS,
	TL2.L2_KOSTL,

	TL1.L1_NODEID,
	TL1.L1_NODENAME,
	TL1.L1_TXTSH,
	TL1.L1_TXTMD,
	TL1.L1_TXTLG
FROM
(SELECT
	NODEID AS L2_NODEID,
	NODENAME AS L2_NODENAME,
	KOKRS AS L2_KOKRS,
	KOSTL AS L2_KOSTL
FROM ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_0101_HIER where tlevel='02') TL2
LEFT OUTER JOIN (SELECT 
	L2.NODEID AS L2_NODEID,
	L1.NODEID AS L1_NODEID,
	L1.NODENAME AS L1_NODENAME,
	L1.TXTSH AS L1_TXTSH,
	L1.TXTMD AS L1_TXTMD,
	L1.TXTLG AS L1_TXTLG
FROM ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_0101_HIER L1 
inner join ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_0101_HIER L2
ON L1.NODEID=L2.PARENTID WHERE L2.TLEVEL='02' AND L1.TLEVEL='01') TL1
WHERE TL2.L2_NODEID=TL1.L2_NODEID) CCHFS 
ON (CCA.KOKRS=CCHFS.L2_KOKRS and CCA.KOSTL=CCHFS.L2_KOSTL)
WHERE CCT.LANGU='E'
)

select * from dim_costcenter_flat