{{
  config(
    materialized='incremental',
    incremental_strategy='merge',
	unique_key='ID'
  )
}}

with dim_costcenter_flat as (
SELECT
	CCA.KOKRS||'-'||CCA.KOSTL||'-'||CCA.DATETO||'-'||NVL(CCT.LANGU,'') as ID,

	CCA.KOKRS,
	CCA.KOSTL,
	CCA.DATETO,

	NVL(CCT.LANGU,'') AS LANGU,

	CCA.DATEFROM,
	CCA.VERAK,
	CCA.BUKRS,
	CCA.GSBER,
	CCA.KOSAR,
	CCA.WAERS,
	CCA.PRCTR,
	CCA.BKZKP,
	CCA.PKZKP,
	CCA.VERAK_USER,
	CCA.KALSM,
	CCA.TXJCD,
	CCA.WERKS,
	CCA.LOGSYSTEM,
	CCA.ERSDA,
	CCA.USNAM,
	CCA.BKZKS,
	CCA.BKZER,
	CCA.BKZOB,
	CCA.PKZKS,
	CCA.PKZER,
	CCA.VMETH,
	CCA.MGEFL,
	CCA.ABTEI,
	CCA.NKOST,
	CCA.KVEWE,
	CCA.KAPPL,
	CCA.KOSZSCHL,
	CCA.LAND1,
	CCA.ANRED,
	CCA.NAME1,
	CCA.NAME2,
	CCA.NAME3,
	CCA.NAME4,
	CCA.ORT01,
	CCA.ORT02,
	CCA.STRAS,
	CCA.PFACH,
	CCA.PSTLZ,
	CCA.PSTL2,
	CCA.REGIO,
	CCA.SPRAS,
	CCA.TELBX,
	CCA.TELF1,
	CCA.TELF2,
	CCA.TELFX,
	CCA.TELTX,
	CCA.TELX1,
	CCA.DATLT,
	CCA.DRNAM,
	CCA.KHINR,
	CCA.CCKEY,
	CCA.KOMPL,
	CCA.STAKZ,
	CCA.OBJNR,
	CCA.FUNKT,
	CCA.AFUNK,
	CCA.CPI_TEMPL,
	CCA.CPD_TEMPL,
	CCA.FUNC_AREA,
	CCA.SCI_TEMPL,
	CCA.SCD_TEMPL,
	CCA.VNAME,
	CCA.RECID,
	CCA.ETYPE,
	CCA.JV_OTYPE,
	CCA.JV_JIBCL,
	CCA.JV_JIBSA,

	CCT.TXTSH,
	CCT.TXTMD,
	CCT.TXTMC,

	CCHFS.L1_TXTSH,
	CCHFS.L1_TXTMD,
	CCHFS.L1_TXTLG,
	CCHFS.L2_TXTSH,
	CCHFS.L2_TXTMD,
	CCHFS.L2_TXTLG,
	CCHFS.L3_TXTSH,
	CCHFS.L3_TXTMD,
	CCHFS.L3_TXTLG,

	CCHFS.L1_NODEID,
	CCHFS.L1_NODENAME,
	CCHFS.L2_NODEID,
	CCHFS.L2_NODENAME,
	CCHFS.L3_NODEID,
	CCHFS.L3_NODENAME,
	CCHFS.L4_NODEID,
	CCHFS.L4_NODENAME

FROM ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_ATTR CCA 
LEFT OUTER JOIN ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_TEXT CCT 
ON (CCA.KOKRS=CCT.KOKRS and CCA.KOSTL=CCT.KOSTL and CCA.DATETO=CCT.DATETO)
LEFT OUTER JOIN (SELECT 
	TL4.L4_NODEID,
	TL4.L4_NODENAME,
	TL4.L4_KOKRS,
	TL4.L4_KOSTL,

	TL3.L3_NODEID,
	TL3.L3_NODENAME,
	TL3.L3_TXTSH,
	TL3.L3_TXTMD,
	TL3.L3_TXTLG,

	TL2.L2_NODEID,
	TL2.L2_NODENAME,
	TL2.L2_TXTSH,
	TL2.L2_TXTMD,
	TL2.L2_TXTLG,

	TL1.L1_NODEID,
	TL1.L1_NODENAME,
	TL1.L1_TXTSH,
	TL1.L1_TXTMD,
	TL1.L1_TXTLG
FROM
(SELECT
	NODEID AS L4_NODEID,
	NODENAME AS L4_NODENAME,
	KOKRS AS L4_KOKRS,
	KOSTL AS L4_KOSTL
FROM ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_0101_HIER where tlevel='04') TL4
LEFT OUTER JOIN (SELECT 
	L4.NODEID AS L4_NODEID,
	L3.NODEID AS L3_NODEID,
	L3.NODENAME AS L3_NODENAME,
	L3.TXTSH AS L3_TXTSH,
	L3.TXTMD AS L3_TXTMD,
	L3.TXTLG AS L3_TXTLG
FROM ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_0101_HIER L3 
inner join ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_0101_HIER L4
ON L3.NODEID=L4.PARENTID WHERE L4.TLEVEL='04' AND L3.TLEVEL='03') TL3
ON TL4.L4_NODEID=TL3.L4_NODEID
LEFT OUTER JOIN (SELECT 
	L3.NODEID AS L3_NODEID,
	L2.NODEID AS L2_NODEID,
	L2.NODENAME AS L2_NODENAME,
	L2.TXTSH AS L2_TXTSH,
	L2.TXTMD AS L2_TXTMD,
	L2.TXTLG AS L2_TXTLG
FROM ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_0101_HIER L2 
inner join ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_0101_HIER L3
ON L2.NODEID=L3.PARENTID WHERE L3.TLEVEL='03' AND L2.TLEVEL='02') TL2
ON TL3.L3_NODEID=TL2.L3_NODEID
LEFT OUTER JOIN (SELECT 
	L2.NODEID AS L2_NODEID,
	L1.NODEID AS L1_NODEID,
	L1.NODENAME AS L1_NODENAME,
	L1.TXTSH AS L1_TXTSH,
	L1.TXTMD AS L1_TXTMD,
	L1.TXTLG AS L1_TXTLG
FROM ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_0101_HIER L1 
inner join ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_0101_HIER L2
ON L1.NODEID=L2.PARENTID WHERE L2.TLEVEL='02' AND L1.TLEVEL='01') TL1
WHERE TL2.L2_NODEID=TL1.L2_NODEID) CCHFS 
ON (CCA.KOKRS=CCHFS.L4_KOKRS and CCA.KOSTL=CCHFS.L4_KOSTL)
WHERE CCT.LANGU='E'
)

select * from dim_costcenter_flat