{{
  config(
    materialized='incremental',
    incremental_strategy='merge',
	unique_key='COSTCENTER_ID'
  )
}}

WITH DIM_COSTCENTER_HIER AS (
SELECT
	nvl(CCH.KOKRS,'SAP-DUMMY')||'-'||nvl(CCH.KOSTL,'SAP-DUMMY') as COSTCENTER_ID,

	NODEID,
	NODENAME,
	TLEVEL,
	LINK,
	PARENTID,
	CHILDID,
	NEXTID,
	INTERVL,
	FIELDNM,
	KOKRS,
	KOSTL,
	TXTSH,
	TXTMD,
	TXTLG
FROM ARRAY_DB.ARRAY_DB_EDW.COSTCENTER_0101_HIER CCH
WHERE (TLEVEL='01') OR (TLEVEL='02' AND (KOKRS is not NULL OR KOSTL is not NULL))
)
--WHERE (KOKRS, KOSTL) IN (SELECT DISTINCT KOKRS, KOSTL FROM DIM_COSTCENTER)

select * from DIM_COSTCENTER_HIER