version: 2

models:
  - name: dim_vendor
    description: This model is for vendor dimension
    columns:
      - name: LIFNR
        tests:
          - unique
          - not_null
  - name: dim_costcenter
    columns:
      - name: COSTCENTER_ID
        tests:
          - unique
          - not_null
      - name: langu
        tests:
          - accepted_values:
              values: ['E']
  - name: fact_generalledger
    tests:
        - relationships:
            column_name: "LIFNR"
            to: ref('dim_vendor')
            field: "LIFNR"
  - name: dim_costcenter_hier
    tests:
        - unique:
            column_name: "KOKRS || '-' || KOSTL"
        - relationships:
            column_name: "KOKRS || '-' || KOSTL"
            to: ref('dim_costcenter')
            field: "KOKRS || '-' || KOSTL"